[package]
name = "sys"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false
default-run = "sys"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.50"
bincode = "1.3"
chrono = "0.4"
chrono-humanize = "0.2.1"
clap = "2.33"
console = "0.14.1"
fd-lock = "3.0.0"
#ftx = { git = "https://github.com/fabianboesiger/ftx", rev = "ce576c74f11c1795eef8cd101735166cb77b7892" }
ftx = { git = "https://github.com/mvines/ftx", rev = "eea60b98cc47052dc0e6c42efe861d8d7cf6fb7f" }
#ftx = { path = "../ftx" }
influxdb-client = "0.1.4"
itertools = "0.10.0"
jup-ag = "0.2.4"
#jup-ag = { path = "../jup_ag" }
lazy_static = "1.4.0"
pickledb = { git = "https://github.com/seladb/pickledb-rs.git", rev = "0.5.0" }
#pickledb = { path = "../pickledb-rs" }
reqwest = "0.11"
rust_decimal = "1.23"
rust_decimal_macros = "1.23"
separator = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_excel_writer = "0.1.9"
solana-clap-utils = "=1.10.8"
solana-cli-config = "=1.10.8"
solana-cli-output = "=1.10.8"
solana-client = "=1.10.8"
solana-logger = "=1.10.8"
solana-remote-wallet = "=1.10.8"
solana-sdk = "=1.10.8"
solana-stake-program = "=1.10.8"
solana-transaction-status = "=1.10.8"
solana-vote-program = "=1.10.8"
spl-associated-token-account = "1.0.3"
spl-token = "3.2.0"
spl-token-lending = { git = "https://github.com/solana-labs/solana-program-library.git", rev = "1d1c2b178b8cf2ed3e28006c27b2ba5b3d039d67" }
strum = { version = "0.23", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "time"] }
tokio-binance = "1.0"
tulipv2-sdk-common = "0.9.5"

[profile.dev]
split-debuginfo = "unpacked"
